### ISSUE TITLE
Dropdown menus not working

### ISSUE THREAD

**Issue by RFLCTNSmusic** [estroBiologist/pluralchum#10]
Hi,

I'm using Pluralchum, but whenever I try to change the default system tag color to that of a system member's color, _the drop-down menus aren't showing up for whatever reason(s)._

Please see the attached screenshot for reference.

Thanks,
RFLCTNS

![Screenshot 2022-07-31 194208](https://user-images.githubusercontent.com/110112548/182050199-8cc690d1-6571-4a53-bd34-4e54968d803b.png)

**Comment by estroBiologist** [comment]
Just tested this myself. My best guess is that it's a BetterDiscord bug? No idea what to do about this, honestly... In the meantime, you can edit `Pluralchum.config.json` in the plugins folder directly. Scrolling all the way down, you'll find a field `tagColourPref`; setting this to 0 should get you the right value, if memory serves. Sorry about that!

**Comment by RFLCTNSmusic** [comment]
Thank you so much!

-RFLCTNS
