### ISSUE TITLE
Message headers never get updated

### ISSUE THREAD

**Issue by Draconizations** [estroBiologist/pluralchum#14]
I left a comment on your tweet announcing the latest version already but it seems it's not just me who's having this issue.

I downloaded the updated version today, the plugin loads fine, but `messageHeaderUpdate()` never actually gets called. So no names ever get fetched and updated.

I'm not sure what's going wrong here but considering the comments point out that particular way of getting message headers could break at any moment, I wouldn't be surprised if that happened!

EDIT: I tried on both windows and linux (fedora), discord Stable 157360 (5cea3cf) (a fresh install on both OS's)

**Comment by vmorrisonwood** [comment]
This is happening to us too - clean BD install and 100% on the right version of PluralChum. Have only tested on macOS.

Stable 157360 (5cea3cf) 
Host 0.0.269 
OS X 10.15.7 (21.6.0)

**Comment by vmorrisonwood** [comment]
> ...ohhh, i might know what's going on here. go ahead and give this version a try, lemme know if it works
> 
> https://cdn.discordapp.com/attachments/846781793834106902/1039964751289122856/Pluralchum.plugin.js

Thank you - this works perfectly! We really appreciate your effort in getting PluralChum back up and working. Hopefully fingers crossed Discord doesn't break it for another good while lol.

**Comment by Draconizations** [comment]
I can confirm that this version works! Thank you so much for the quick reply

**Comment by estroBiologist** [comment]
glad to hear it! i'll release it as a patch real quick 👍
