### ISSUE TITLE
Pluralchum automatically disabling itself.

### ISSUE THREAD

**Issue by SeraDroid** [estroBiologist/pluralchum#16]
As the name suggests, Pluralchum is for some reason automatically disabling itself.
![image](https://user-images.githubusercontent.com/119632759/205166806-a4893f37-9431-4571-a313-5e3a884b35d3.png)
As you can see in this image^, Pluralchum is active.
I leave that page, however...
![image](https://user-images.githubusercontent.com/119632759/205166915-d6be4f57-277c-41db-9a74-e4ebe86d9a56.png)
And when I come back, it's back off.

**Comment by rladenson** [comment]
I'm also having this issue, when I turn it on (or off) it shows both the "pluralchum is enabled" and "pluralchum is disabled" messages at the same time and it won't stay on
