### ISSUE TITLE
[Feature request] Vencord or other client mod port?

### ISSUE THREAD

**Issue by JinglBells** [estroBiologist/pluralchum#20]
We'd love to use this but we use Vencord ( a more lightweight easy-to-use mod for discord) but unfortunately, there's no compatibility layer. would love a port but know its difficult so no biggies ^^

**Comment by estroBiologist** [comment]
yeah im gonna be real i can barely muster the energy to maintain one version of this plugin lol

if anyone wants to make and maintain a fork they are 100% welcome and greatly appreciated but i personally can't afford to do this. apologies

**Comment by estroBiologist** [comment]
whoops wrong closure reason
