### ISSUE TITLE
System tags can be incorrectly displayed

### ISSUE THREAD

**Issue by RokonShimo** [estroBiologist/pluralchum#34]
![image](https://github.com/estroBiologist/pluralchum/assets/43028444/c6146594-b8c7-4972-aaef-4d9fe3373b70)
![image](https://github.com/estroBiologist/pluralchum/assets/43028444/327a1f86-c6ec-4a01-9062-e37ab71e5da7)

When a system has a servertag enabled, the plugin will often display both the servertag and base system tag, truncating the servertag. This truncation behaviour does not go away when the plugin is disabled and requires a hard refresh to rectify.

![image](https://github.com/estroBiologist/pluralchum/assets/43028444/13ada2e4-f0e8-44c3-87e3-c66bd317375c)
![image](https://github.com/estroBiologist/pluralchum/assets/43028444/ad44855e-bfb8-4458-aaa3-fcec68c1859f)
^ how these should appear in vanilla discord
![image](https://github.com/estroBiologist/pluralchum/assets/43028444/0d1b67fb-0669-4f49-b7ae-490bb5fb67c1)
![image](https://github.com/estroBiologist/pluralchum/assets/43028444/204f38b0-72b9-4bc9-98c2-01dd19f59ad1)
^ how they appear after the plugin is disabled

**Comment by ariagivens** [comment]
Unfortunately, servertags are going to remain an issue for quite some time. PluralKit (for good reasons) doesn't provide a way to query guild settings like servername and servertag unless you have that system's token. So the plugin just doesn't have enough information to render everything correctly. I'm working on some improvements that handle the complexities of unicode better and we should see some improvement on issues like these, but it will never be totally fixed unless there's a change on PK's side.
