### ISSUE TITLE
Settings menu isn't fully usable

### ISSUE THREAD

**Issue by mothdotmonster** [estroBiologist/pluralchum#35]
You can't click the "Theme" option for system tag color. It's hidden behind the other tab.
![Screenshot from 2023-09-27 11-51-09](https://github.com/estroBiologist/pluralchum/assets/82258270/8abd8d81-b1c3-4b20-ab45-920e02bdd065)

**Comment by ariagivens** [comment]
Thanks for the report, fixed in 2.1.3!
