### ISSUE TITLE
Formatting issues

### ISSUE THREAD

**Issue by HarmonyHypoxia** [estroBiologist/pluralchum#37]
Possible issue created by the new update that broke everything? Normal displaynames now look like this 
![image](https://github.com/estroBiologist/pluralchum/assets/132531054/a14af4a1-eac8-419f-89b5-ff9c0d7510f5)

**Comment by ariagivens** [comment]
Yeah there are a number of styling issues that broke with the latest update. I'll work on fixing them when I get the time.
