### ISSUE TITLE
PK badge is unstyled?

### ISSUE THREAD

**Issue by Nidoskull** [estroBiologist/pluralchum#46]
![image](https://github.com/estroBiologist/pluralchum/assets/109077284/27382a29-6fff-4eab-bf97-fde1b317606d)
That doesn't look *quite* right to me x)

**Comment by Draconizations** [comment]
came in here to check if someone had reported this already. it broke with a recent discord update

**Comment by seylerius** [comment]
Discord broke this again. Thank you, Discord, for making more work for our devs.

**Comment by seylerius** [comment]
Can we reopen this?
