### ISSUE TITLE
Unable to download plugin library

### ISSUE THREAD

**Issue by assacidic** [estroBiologist/pluralchum#5]
Whenever I go to the link provided, it gives me "Unable to connect

An error occurred during a connection to betterdiscord.net.

    The site could be temporarily unavailable or too busy. Try again in a few moments.
    If you are unable to load any pages, check your computer’s network connection.
    If your computer or network is protected by a firewall or proxy, make sure that Firefox is permitted to access the Web."

is the site temporarily down? Ive checked my firewall and connections, and nothing was wrong there.

**Comment by transdisaster** [comment]
Are you using the link from the plugin's pop-up?
