### ISSUE TITLE
Recent Discord change regresses #46

### ISSUE THREAD

**Issue by seylerius** [estroBiologist/pluralchum#51]
A recent change Discord made seems to have regressed the issue in #46, causing the PK badge to once again be unstyled.

**Comment by transdemonic** [comment]
I am also having this issue, do we know if it will ever be fixed?

**Comment by TELEK1NET1C** [comment]
having the issue as well :(

**Comment by MegaShinySnivy** [comment]
Anyone heard from @estroBiologist ? Would be nice to get this closed :grin:

**Comment by estroBiologist** [comment]
apologies for the delay - i don't have much time to maintain PluralChum myself nowadays. just merged the fix, i'll publish a hotfix release in a minute
